PropertyManagement.MVC/Controllers/CommentRepliesController.cs
using Microsoft.AspNet.Identity;
using PropertyManagement.Data;
using PropertyManagement.Models.Replies;
using PropertyManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyManagement.Controllers
{
    public class CommentRepliesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CommentReplies
        public ActionResult Index()
        {
            var svc = CreateCommentRepliesService();
            var cReply = svc.GetCommentReplies();
            return View(cReply);
        }

        // GET: CommentReplies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CommentReplies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReplyCreate reply)
        {
            if (!ModelState.IsValid)
                return View(reply);

            var svc = CreateCommentRepliesService();

            if (svc.ReplyCommentCreate(reply))
            {
                TempData["SaveResult"] = "Reply was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Reply could not be created.");

            return View(reply);
        }

        // GET: CommentReplies/Details/{id}
        public ActionResult Details(int? id)
        {
            var svc = CreateCommentRepliesService();
            var reply = svc.GetCommentRepliesById(id);
            return View(reply);
        }

        // GET: CommentReplies/Edit/{id}
        public ActionResult Edit(int id)
        {
            var svc = CreateCommentRepliesService();
            var model = svc.GetCommentRepliesById(id);
            var reply = new ReplyEdit
            {
                Content = model.Content,
            };

            return View(reply);
        }

        // POST: CommentReplies/Edit/{id}
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ReplyEdit reply)
        {
            if (!ModelState.IsValid)
            {
                return View(reply);
            }

            if (reply.ReplyId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(reply);
            }

            var svc = CreateCommentRepliesService();

            if (svc.UpdateReply(reply))
            {
                TempData["SaveResult"] = "Reply review was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Reply review could not be updated.");
            return View(reply);
        }

        // GET: CommentReplies/Delete/{id}
        public ActionResult Delete(int id)
        {
            var svc = CreateCommentRepliesService();
            var reply = svc.GetCommentRepliesById(id);
            return View(reply);
        }

        // POST: CommentReplies/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var svc = CreateCommentRepliesService();
            svc.DeleteReply(id);
            TempData["SaveResult"] = "Reply review was deleted.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ReplyService CreateCommentRepliesService()
        {
            var userId = User.Identity.GetUserId();
            var svc = new ReplyService(userId);
            return svc;
        }
    }
}

PropertyManagement.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyManagement.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }
    }
}

PropertyManagement.MVC/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PropertyManagement.Data;
using PropertyManagement.Models.Listings;
using PropertyManagement.Services;

namespace PropertyManagement.Controllers
{
    public class ListingsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Listings
        public ActionResult Index()
        {
            var svc = CreateListingService();
            var listing = svc.GetListings();
            return View(listing);
        }

        // GET: Listings/Create
        public ActionResult Create()
        {
            var svcP = CreatePropertyService();
            ViewBag.Properties = svcP.GetProperties();
            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ListingCreate listing)
        {
            if (!ModelState.IsValid)
                return View(listing);

            var svc = CreateListingService();

            if (svc.ListingCreate(listing))
            {
                TempData["SaveResult"] = "Your listing was created.";
                return RedirectToAction("Index");
            };
            ModelState
                .AddModelError("", "Property could not be created.");

            return View(listing);
        }

        // GET: Listings/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateListingService();
            var listing = svc.GetListingById(id);
            return View(listing);
        }

        // POST: Listings/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var svc = CreateListingService();
            svc.DeleteListing(id);
            TempData["SaveResult"] = "Listing was deleted.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ListingService CreateListingService()
        {
            var userId = User.Identity.GetUserId();
            var svc = new ListingService(userId);
            return svc;
        }

        private PropertyService CreatePropertyService()
        {
            var userId = User.Identity.GetUserId();
            var svcP = new PropertyService(userId);
            return svcP;
        }
    }
}

PropertyManagement.MVC/Controllers/ReviewRepliesController.cs
using Microsoft.AspNet.Identity;
using PropertyManagement.Data;
using PropertyManagement.Models.Replies;
using PropertyManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyManagement.Controllers
{
    public class ReviewRepliesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ReviewReplies
        public ActionResult Index()
        {
            var svc = CreateReviewRepliesService();
            var rReply = svc.GetReviewReplies();
            return View(rReply);
        }

        // GET: ReviewReplies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReviewReplies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReplyCreate reply)
        {
            if (!ModelState.IsValid)
                return View(reply);

            var svc = CreateReviewRepliesService();

            if (svc.ReplyReviewCreate(reply))
            {
                TempData["SaveResult"] = "Reply was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Reply could not be created.");

            return View(reply);
        }

        // GET: ReviewReplies/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateReviewRepliesService();
            var reply = svc.GetReviewRepliesById(id);
            return View(reply);
        }

        // GET: ReviewReplies/Edit/{id}
        public ActionResult Edit(int id)
        {
            var svc = CreateReviewRepliesService();
            var model = svc.GetReviewRepliesById(id);
            var reply = new ReplyEdit
            {
                Content = model.Content,
            };

            return View(reply);
        }

        // POST: ReviewReplies/Edit/{id}
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ReplyEdit reply)
        {
            if (!ModelState.IsValid)
            {
                return View(reply);
            }

            if (reply.ReplyId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(reply);
            }

            var svc = CreateReviewRepliesService();

            if (svc.UpdateReply(reply))
            {
                TempData["SaveResult"] = "Reply review was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Reply review could not be updated.");
            return View(reply);
        }

        // GET: ReviewReplies/Delete/{id}
        public ActionResult Delete(int id)
        {
            var svc = CreateReviewRepliesService();
            var reply = svc.GetReviewRepliesById(id);
            return View(reply);
        }

        // POST: ReviewReplies/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var svc = CreateReviewRepliesService();
            svc.DeleteReply(id);
            TempData["SaveResult"] = "Reply review was deleted.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ReplyService CreateReviewRepliesService()
        {
            var userId = User.Identity.GetUserId();
            var svc = new ReplyService(userId);
            return svc;
        }
    }
}

PropertyManagement.MVC/Controllers/VendorReviewsController.cs
using Microsoft.AspNet.Identity;
using PropertyManagement.Data;
using PropertyManagement.Models.Reviews;
using PropertyManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropertyManagement.Controllers
{
    public class VendorReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VendorReviews
        public ActionResult Index()
        {
            var svc = CreateVendorReviewService();
            var vReview = svc.GetVendorReviews();
            return View(vReview);
        }

        // GET: VendorReviews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VendorReviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReviewCreate review)
        {
            if (!ModelState.IsValid)
                return View(review);

            var svc = CreateVendorReviewService();

            if (svc.ReviewVendorCreate(review))
            {
                TempData["SaveResult"] = "Vendor was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Vendor could not be created.");

            return View(review);
        }

        // GET: VendorReviews/Details/{id}
        public ActionResult Details(int id)
        {
            var svc = CreateVendorReviewService();
            var review = svc.GetVendorReviewsById(id);
            return View(review);
        }

        // GET: VendorReviews/Edit/{id}
        public ActionResult Edit(int id)
        {
            var svc = CreateVendorReviewService();
            var model = svc.GetVendorReviewsById(id);
            var review = new ReviewEdit
            {
                Title = model.Title,
                Content = model.Content
            };

            return View(review);
        }

        // POST: VendorReviews/Edit/{id}
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ReviewEdit review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }

            if (review.ReviewId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(review);
            }

            var svc = CreateVendorReviewService();

            if (svc.UpdateReview(review))
            {
                TempData["SaveResult"] = "Vendor review was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Vendor review could not be updated.");
            return View(review);
        }

        // GET: VendorReviews/Delete/{id}
        public ActionResult Delete(int id)
        {
            var svc = CreateVendorReviewService();
            var review = svc.GetVendorReviewsById(id);
            return View(review);
        }

        // POST: VendorReviews/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var svc = CreateVendorReviewService();
            svc.DeleteReview(id);
            TempData["SaveResult"] = "Vendor review was deleted.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ReviewService CreateVendorReviewService()
        {
            var userId = User.Identity.GetUserId();
            var svc = new ReviewService(userId);
            return svc;
        }
    }
}

PropertyManagement.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>@ViewBag.Title - The Story of Lovely Living Property Management </h2>

<p>This will be where we write about our orgin story</p>
<p>Who started it - Brief origin story of founder(s)</p>
<p>What we do - Our Services</p>
<p>Why we do it - Our Mission</p>
<p>Maybe some pictures of the facility</p>

<p>We will also include an employee list that will showcase a headshot, a personal biography, and a description of what they do at the company.</p>
<p>Create a table where the headshot is on the left and then you have two sections on the right for the writing.</p>

PropertyManagement.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title</h2>

@*Float div to left side of screen*@
<div>
    <h5>Feel free to fill out the form below or reach us directly by calling or emailing us. <br /> We look forward to hearing from you!</h5>
    <h5>Direct Support is available Monday through Friday, 8am to 7pm EST</h5>
    <p>Would be nice to implement a submission form</p>
</div>

@*Float div to right side of screen*@
<div>
    <address>
        <p>Would be nice to implement a google map of our location</p>
        Lovely Living Property Management<br />
        123 Main St.<br />
        Fort Wayne, IN 46802<br />
    </address>

    <address>
        <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Phone Number:</strong> 260.123.4567 <br />
        <strong>Toll Free Number:</strong> 800.123.4567<br />
        <strong>Fax:</strong> 800.987.6543
    </address>
</div>

PropertyManagement.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>#1 Property Management Company in Fort Wayne</h1>
    <p class="lead">Lovely Living Property Management launched in 2020.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    <ul>
        <li>@Html.ActionLink("Properties", "Index", "Properties")</li>
        <li>@Html.ActionLink("Users", "Index", "ApplicationUser")</li>
        <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
        <li>@Html.ActionLink("Comment Replies", "Index", "CommentReplies")</li>
        <li>@Html.ActionLink("Vendors", "Index", "Vendors")</li>
        <li>@Html.ActionLink("Vendor Reviews", "Index", "VendorReviews")</li>
        <li>@Html.ActionLink("Company Reviews", "Index", "VendorCompanys")</li>
        <li>@Html.ActionLink("Review Replies", "Index", "ReviewReplies")</li>
    </ul>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Listings</h2>
        <p>
            Check out all of our listings.
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Show Listings &raquo;"), "Index", "Listings", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
    <div class="col-md-4">
        <h2>Reviews</h2>
        <p>
            Give us a review or check out reviews by others.
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Show Reviews &raquo;"), "Index", "Reviews", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
    <div class="col-md-4">
        <h2>Vendors</h2>
        <p>
            Check out our approved vendors.
        </p>
        <p>@Html.ActionLink(HttpUtility.HtmlDecode("Show Vendors &raquo;"), "Index", "Vendors", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h4>Review 1</h4>
        <p>
            random review
        </p>
    </div>
    <div class="col-md-4">
        <h4>Review 2</h4>
        <p>
            random review
        </p>
    </div>
    <div class="col-md-4">
        <h4>Review 3</h4>
        <p>
            random review
        </p>
    </div>
</div>

PropertyManagement.MVC/Views/Home/Services.cshtml
@{
    ViewBag.Title = "Our Services";
}

<h2>@ViewBag.Title</h2>

<p>This is where we will have a detailed list of all of the services we provide and the respective descriptions</p>